# docker compose version
version: "3.7"

# membuat service
services:
  # service item-app untuk aplikasi
  item-app:
    # pull image dari github package
    image: ghcr.io/hendry16/item-app:v1
    # publish port 80 di localhost dari port 8080 di container
    ports:
      - 80:8080
    # menunggu service item-db menyiapkan container terlebih dahulu
    depends_on:
      - item-db
    # menjalankan service kembali secara otomatis setiap kali berhenti
    restart: always


  # service item-db untuk database
  item-db:
    # pull image mongo:3
    image: mongo:3
    # menggunakan volume app-db dengan lokasi /data/db 
    volumes:
      - app-db:/data/db
    # menjalankan service kembali secara otomatis setiap kali berhenti
    restart: always

# define volume
volumes:
  # membuat volume dengan nama app-db
  app-db: